{% set data= load_setup_py_data() %}
package:
  name: ts-hvac
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_hvac = lsst.ts.hvac.csc:run_hvac

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-utils
    - pandas
    - paho-mqtt
    - lxml
  source_files:
    - python
    - bin
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
    - pandas
    - paho-mqtt
    - lxml
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - pandas
    - paho-mqtt
    - lxml
